[versions]
kotlin = "2.1.0"
android-minSdk = "24"
android-compileSdk = "35"
androidGradlePlugin = "8.6.1"
jetbrainsCompose = "1.7.3"
dokka = "2.0.0"
annotation = "1.9.1"
oshiCore = "6.7.1"
startupRuntime = "1.2.0"
androidXCore = "1.15.0"
equinox = "1.0.9"

[libraries]
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidXCore" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshiCore" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrainsCompose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrainsCompose" }
x_cdn-jsdelivr-net_npm_ua-parser-js = { module = "https://cdn.jsdelivr.net/npm/ua-parser-js" }
equinox-compose = { module = "io.github.n7ghtm4r3:equinox-compose", version.ref = "equinox" }
equinox-core = { module = "io.github.n7ghtm4r3:equinox-core", version.ref = "equinox" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }